version: "2"

services:
  db:
    image: mysql:8.1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - mysql_data:/var/lib/mysql

  hive-meta:
    image: hive-meta:latest
    ports:
      - 9083:9083
    depends_on:
      - db

  hive-hs2:
    image: hive-hs2:latest
    ports:
      - 10000:10000
    depends_on:
      - hive-meta



volumes:
  mysql_data:
