version: "2"

services:
  # mariadb:
  #   image: mariadb:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: metastore_db
  #     MYSQLD_MAX_CONNECTIONS: 500
  #   volumes:
  #     - ./custom-my.cnf:/etc/mysql/conf.d/custom-my.cnf
  db:
    image: mysql:8.1
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - mysql_data:/var/lib/mysql

  # make sure that you specify correct volume to be mounted
  # minio:
  #   image: minio/minio
  #   environment:
  #     - MINIO_ACCESS_KEY=accesskey
  #     - MINIO_SECRET_KEY=secretkey
  #   volumes:
  #     - /data1/minio:/data
  #   ports:
  #     - 9000:9000
  #   command: server /data

  # nginx_with_curl:
  #   container_name: nginx_curl
  #   image: nginx_curl:latest
  #   expose:
  #     - 80
  #   ports:
  #     - "8099:80"

  # hive-metastore:
  #   image: hive-metastore:latest
  #   ports:
  #     - 9083:9083
  #   depends_on:
  #     - db


volumes:
  mysql_data:
